### PR TITLE
Xingzhuo testing zmq comm

### PR DESCRIPTION
**Pull request by Wanchai290**
Recreation of PR #34 that had an older history problem. This PR is the same as the one mentioned but with the history fixed.

### CODE REVIEW

**Comment by Wanchai290** [comment]
I couldn't test out the file at home, could you fetch the latest software release and test it out using your new script ?

**Comment by XingpingGY** [comment]
Sorry for my late response. I am in Kumamoto for the conference here. Your work will be presented as well, congratulations! I will be back at lab next Friday. I will test it once I am back. I am sorry that I have you waiting so long......

**Comment by Wanchai290** [comment]
No worries, take your time ! I will be available if you or Tixier-Mita sensei have any questions before the presentation

**Comment by XingpingGY** [comment]
Thank you very much! Tixier-Mita sensei is presenting the work and you did a really good job! It seems no problem and the presentation is going smoothly and well.

**Comment by XingpingGY** [comment]
It seems that you did not change the file `docs/custom_integrations/tixier_mita_lab/custom_raspberrypi_headless.py` with the new structure you developed with zmq library. Could you please modify it as well?

**Comment by Wanchai290** [comment]
You're right I have forgotten to do it. I will be implementing your changes in a new issue and will close this PR once we are sure that the new modifications on the RaspberryPi works well at the laboratory's setup.

**Pull request closed without merging**
