### PR TITLE
Develop_using zmq lib

### PR DESCRIPTION
**Pull request by XingpingGY**
Sorry for that I am not so familiar with pull request. This time I pulled request in the develop branch. I revised the custom_raspberrypi_headless_zmq.py file to change the communication process with zmq lib and add a client file from the laptop end for testing.

### CODE REVIEW

**Comment by XingpingGY** [comment]
Could you pls rewrite the communication protocol part using the zmq lib? Or you can tell me which parts need to be revised especially from the client side (laptop software side). The process to display the image from a distant server on the qt_gui is difficult for me to understand so I am not sure which parts to be polished using zmq lib rather than basic tcp.

**Comment by Wanchai290** [comment]
Yes, I will try to do this when I get the time, it should not take too long.

As for the pull request, it seems you started your custom branch from master, applied some commits onto it and then created the PR for develop ? This could explain the number of commits this PR creates. Since the history of both `master` and `develop` are different, you are trying to "fuse" part of the history of master onto develop, which causes the high number of commits.
To fix this, you need to :
- Create the branch from the develop branch
- Apply the commits (using `git cherry-pick [commit_hash]` for example)
- Re-create the PR for this new branch

Sorry to have you do this, but I don't want to rewrite the history of `develop` ^^'

**Comment by Wanchai290** [comment]
Actually the mistake was simpler than that. You forgot to pull the latest changes before committing haha. Your version of the repository was older than mine, so Git doesn't really understand and the conflicting histories cause a massive merge. I have re-created the PR you've made with the current changes from `develop`, please tell me if they are correct. Check out #35

**Comment by XingpingGY** [comment]
Sorry for the problem that I made, thanks for the new PR haha, it is correct!

**Pull request closed without merging**
